config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :pets, only: [:index, :new, :create, :show]
  
  root to: "writes#new"
  resources :writes, only: [:index, :new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
  validates :name, presence: true
  belongs_to :user

  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :pets

end

app/models/write.rb
class Write < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :authenticate_user!, only: [:create] # ユーザーのログインをチェック

  def index
    @pets = Pet.all
  end

  def new
    @pet = Pet.new
  end

  def create
    if user_signed_in? 
      @pet = current_user.pets.build(pet_params) 
    if @pet.save
      redirect_to root_path
    else
      render :new
    end
    else 
      redirect_to new_user_session_path, alert: "ログインしてください。"
    end
  end


  def show
    @pet = Pet.find(params[:id])
  end


  private
  def pet_params
    params.require(:pet).permit(:name, :gender, :kind, :birthday, :image).merge(user_id: current_user.id)
  end
end

app/controllers/writes_controller.rb
class WritesController < ApplicationController

  def index
    @writes = Write.all
  end

  def new
    @write = Write.new
  end

  def create
    write_params = params.require(:write).permit(:icon, :memo, :start_time, :schedule)
    if
      write_params[:start_time].blank?
      write_params[:start_time] = Time.current
    end
    @write = Write.create(write_params)
    if
      @write.save
      redirect_to write_path(@write), notice: 'Write was successfully created.'
    else
      render :new
    end
  end

  def show
    @target_date = Date.parse(params[:id])
    @writes = Write.where(start_time: @target_date.beginning_of_day..@target_date.end_of_day)
  end

  private

  def write_params
     params.require(:write).permit(:icon, :start_time, :memo, :schedule, :created_at)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>fam のーと</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="user.css">
    <title>fam のーと</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Aoboshi+One&family=Open+Sans:wght@300&family=Potta+One&display=swap" rel="stylesheet">
  </head>


  <body>
    <header>
      <div class="header">
        <div class="title">ペット登録</div>
        <!--input type="submit" value="あとで登録" class="button"-->
      </div>
    </header>

  <div class="user_content">
  <div class="user_contents">
    <%= form_with(model: @pet, local: true) do |form| %>

      <div class="pet-form">
        <%= form.label :imag, "写真" %><br />
        <%= form.file_field :image, class: "pet_image" %><br>
      </div>

      <div class="pet-form">
        <%= form.label :name, "ペット名" %><br />
        <%= form.text_field :name, id:"name"%>
      </div>

      <div class="pet-form">
        <%= form.label :gender, "性別" %><br />
        <%= form.radio_button :gender, :"オス" %>
        <%= form.label :gender_オス, "オス" %>
        <%= form.radio_button :gender, :"メス" %>
        <%= form.label :gender_メス, "メス" %>
        <%= form.radio_button :gender, :"わからない" %>
        <%= form.label :gender_わからない, "わからない" %>
      </div>

      <div class="pet-form">
        <%= form.label :kind, "種類" %><br />
        <%= form.text_field :kind, id:"kind" %>
      </div>

      <div class="pet-form">
        <%= form.label :birthday, "誕生日" %><br />
        <%= form.date_field :birthday, id:"birthday" %>
      </div> 

      <!--<div class="pet-form">
        <%= form.label :aniversary, "記念日" %><br />
        <%= form.date_field :aniversary, id:"aniversary" %>
      </div> 

      <div class="pet-form">
        <%= form.label :aniversary_name, "記念日名" %><br />
        <%= form.text_field :aniversary_name, id:"aniversary_name" %>
      </div> -->

      <div class="actions">
        <%= form.submit "ＯＫ！", class: :form__btn  %>
      </div>

    <% end %>
  </div>
  </div>
  </body>
  </html>

app/views/pets/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="writes.css">
    <title>fam のーと</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Aoboshi+One&family=Open+Sans:wght@300&family=Potta+One&display=swap" rel="stylesheet">
  </head>

  <body>
    <header>
      <div class="header1">
        <div class="title1"><%= "#{@pet.name}情報" %></div>
        <div class="header_button">
        <%= link_to image_tag('edit.png'), writes_path(@writes) %><!--編集ページへ-->
        <%= link_to image_tag('addition.png'), writes_path(@writes) %><!--追加ページへ-->
        <%= link_to image_tag('return.png'), writes_path(@writes) %><!--戻る-->

        </div>
      </div>
   </header>

    <div class="pet_content_up">
      <div class='pet_img'>
      <%= image_tag @pet.image,class:"pet-box-img" %>

    </div>

    <div class="pet_content_down">
     <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @pet.name %></td>
          </tr>
          <tr>
            <th class="table__col1">性別</th>
            <td class="table__col2"><%= @pet.gender %></td>
          </tr>
          <tr>
            <th class="table__col1">種類</th>
            <td class="table__col2"><%= @pet.kind %></td>
          </tr>
          <tr>
            <th class="table__col1">誕生日</th>
            <td class="table__col2"><%= @pet.birthday %></td>
          </tr>
          <tr>
            <th class="table__col1">ユーザー名</th>
            <td class="table__col2"><%= @pet.user.name %></td><!--ユーザー名にする-->
          </tr>
        </tbody>
      </table>
     </div>
  </body>
</html>

app/views/writes/index.html.erb
<%= month_calendar events: @writes do |date, writes| %>
  <%= link_to date.day, write_path(id: date.to_s) %>

  <% day_writes = writes.select { |write| write.start_time.to_date == date } %>
  <% has_star_icon = false %>
  <% day_writes.each do |write| %>
    <% if write.icon.present? && !has_star_icon %>
      <div>
        <%= link_to write_path(id: date.to_s) do %> <!-- 日付の詳細ページに遷移 -->
          <%= image_tag('star.png') %>
        <% end %>
      </div>
      <% has_star_icon = true %>
    <% end %>
  <% end %>
<% end %>

app/views/writes/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>fam のーと</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Aoboshi+One&family=Open+Sans:wght@300&family=Potta+One&display=swap" rel="stylesheet">
  </head>

  <body>
    <header>
      <div class="header1">
        <div class="title1">記録</div>
        <div class="header_button">
          <%= link_to image_tag('time.png'), write_path(id: Date.today.to_s) %><!--詳細ページへ-->
          <%= link_to image_tag('calender.png'), writes_path(@writes) %><!--カレンダーへ-->
        </div>
      </div>
    </header>

 <%= form_with(model: @write, local: true, method: :post) do |form| %>
    <div class="writes_content">
      <div class="writes_content_top">
        <div style="white-space: nowrap">
          <div class="icon_1">
          
          <%= form.radio_button :icon, :"meal" %>
          <%= form.label :icon_meal, "meal" %>
          <%= form.radio_button :icon, :"poop" %>
          <%= form.label :icon_poop, "poop" %>
          <%= form.radio_button :icon, :"pee" %>
          <%= form.label :icon_pee, "pee" %>
          <%= form.radio_button :icon, :"walk" %>
          <%= form.label :icon_walk, "walk" %>
          </div>


          <div class="icon_2">
          <%= form.radio_button :icon, :"vomit" %>
          <%= form.label :icon_vomit, "vomit" %>
          <%= form.radio_button :icon, :"shampoo" %>
          <%= form.label :icon_shampoo, "shampoo" %>
          <%= form.radio_button :icon, :"trimming" %>
          <%= form.label :icon_trimming, "trimming" %>
          <%= form.radio_button :icon, :"medicine" %>
          <%= form.label :icon_medicine, "medicine" %>
          </div>
        </div>
      </div>

      <div class="writes_content_bottom">
        <div class="write-form">
          <%= form.label :memo, "メモ" %><br />
          <%= form.text_field :memo, id:"memo" %>
        </div>
        <div class="write-form">
          <%= form.label :start_time, "日時" %><br />
          <%= form.datetime_field :start_time, id:"start_time", default: Time.current %>
        </div>
        <div class="write-form">
          <%= form.label :schedule, "スケジュール" %><br />
          <%= form.text_field :schedule, id:"schedule" %>
        </div>
        <div class="actions">
          <%= form.submit "ＯＫ！", class: :write_form__btn  %>
        </div>
      </div>
<% end %>
  </body>
</html>

app/views/writes/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag 'writes' %>
    <title>fam のーと</title>
  </head>

<body>
  <header>
    <div class="header2">
      <div class="title2">
       <%= @target_date &.strftime('%Y年 %m月 %d日') %>
      </div>

      <div class="header_button">
        <%= link_to image_tag('addition1.png'), root_path %>
        <%= link_to image_tag('calender.png'), writes_path(@writes) %><!--カレンダーへ-->
      </div>
    </div>
  </header>

  <div class="writes_day-main">
    <div class="writes-day_contents">
      <div class="birthday-content">
        <%= image_tag 'happy.png' ,size: "300x100"%> <!--もし記念日なら表示-->
      </div>


<% if @write.present? %>
  <div class="icon">
    <%= image_tag 'schedule.png' %>
  </div>
  <div class="schedule-content">
    <ul>
      <% @writes.each do |write| %>
        <li><%= write.schedule %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
      
<% if @writes.present? %>
  <div class="icon">
    <%= image_tag 'star.png' %>
  </div>
  <div class="star-content">
    <ul>
      <% @writes.each do |write| %>
        <li>
          <%= write.icon %>
          <% if write.start_time %>
            <%= write.start_time.strftime("%H:%M") %>
          <% else %>
            <%= write.created_at.strftime("%H:%M") %>
          <% end %>
          <%= write.memo %>
        </li>
      <% end %>
    </ul>
  </div>
<% else %>
  <p>記録がありません</p>
<% end %>

    </div>
  </div>
</body>
</html>